version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=sql12.freesqldatabase.com
      - DB_USER=sql12777636
      - DB_PASSWORD=7YypCXcYQm
      - DB_NAME=sql12777636
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=invest
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 